version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "productdatabase"
    ports:
      - "5432:5432"